### PR TITLE
updated, cleaned up, and rearranged gradles and dependencies

### PR DESCRIPTION
**Pull request by TacoTheDank**
its quite a mess tbh, so i felt this had to be done

Signed-off-by: TacoTheDank <SkytkRSfan3895@gmail.com>

### CODE REVIEW

**Comment by PerfectSlayer** [comment]
Hi @TacoTheDank,

Thanks for your review! And you feel right, it is a good thing to try to improve this part of the project.
I am not a professional Android developer, more a Java one so I am more ease with Maven than Gradle and any help on this subject is welcome!
I already spend a lot of energy to cut the app in module, removing deprecated dependencies and some Gradle script and having decent incremental build time so I enjoy having some help here 👍 

Sadly, I won't have time to merge it until two weeks. But I planned a review as soon as I have free time 😉

**Comment by TacoTheDank** [comment]
kk

**Comment by PerfectSlayer** [comment]
I had to revert to gradle 4.4 as on demand build is not supported by Android gradle plugin since 4.6 version.
I also had an issue with a `plugins` declaration to late in the build file.

**Comment by PerfectSlayer** [comment]
The new version of Gradle plugin was release yesterday.
I just did the update ( d7fb0a8392d3f1300b486d51dc5d2aa562976432 ) and Gradle 4.10 now works fine!

**Comment by TacoTheDank** [comment]
yay

**Pull request merged**
