### PR TITLE
Update for French translation

### PR DESCRIPTION
**Pull request by xerta555**
Hello,
Here is an update for the French translation.

You quote translators in your app if i'm remember good, thanks in advance to not write `xerta555`, but `Rom`.

### CODE REVIEW

**Comment by xerta555** [comment]
>  You could include a commit to the mentions as well to be sure to be credited correctly.

Ok and in winch file i must commit a change for my name ?

**Comment by Vankog** [comment]
Translators are mentioned in the https://github.com/AdAway/AdAway/blob/master/README.md

**Comment by Vankog** [comment]
As you can see, the Strings were changed just recently and created conflicts. Could you please rebase?

**Comment by xerta555** [comment]
@Vankog Hello, so i have fix the problem and my translation can be merged.

> Translators are mentioned in the https://github.com/AdAway/AdAway/blob/master/README.md

About my name in the translators list, if i understand corectly, i need to install a software on a linux just to write my name ??

**Comment by Vankog** [comment]
No, a text editor is sufficient to open the MD file and edit the code.

**Comment by xerta555** [comment]
>No, a text editor is sufficient to open the MD file and edit the code.

sorry but i don't understand where in the MD file i can see the list of the translators..

**Comment by Vankog** [comment]
Oops, sorry I must have looked at the wrong repository or something. You are right, there is no contributor list for translators.
But that doesn't mean you couldn't start a section for that. ;-)

**Comment by PerfectSlayer** [comment]
Hi @xerta555 and @Vankog 
Thanks Romain for the French translation update 👍  I could have done myself but I did not find to time to.
In fact, I really struggle with the translations on this project. They comes from [Transifex](https://www.transifex.com/free-software-for-android/adaway/) and GitHub PR (sometimes from issues 😅).

@Vankog I saw you very active on the PR related to translations. Are you interested to join the team to handle them?
It means be able to update transifex localizations, commit in the repository by yourself, propose ways to integrate with Travis, etc… If you want, I can talk to the team about it 😉 It would be very useful to the project!

**Comment by Vankog** [comment]
@PerfectSlayer I'd love to. This way translations could be integrated faster, before they get a bit stale.

**Comment by PerfectSlayer** [comment]
Awesome! I reached @dschuermann to check if he agrees and get more details about the Transifex process.
I will get back to you as soon as I have the information :wink:

**Pull request closed without merging**
