### PR TITLE
Update croatian language

### PR DESCRIPTION
**Pull request by muzena**

### CODE REVIEW

**Comment by muzena** [comment]
@PerfectSlayer 
Can you please merge this.

**Comment by PerfectSlayer** [comment]
Hi @muzena 
The locations are usually updated through Transifex.
Could you check the README about it: https://github.com/AdAway/AdAway#translations ?

**Comment by muzena** [comment]
@PerfectSlayer 
I update/translate this on transifex, this is file from transifex.
Can you pull these files from transifex because translation is defective, look like it was translated with google translator. Last translation update was before 11 month.

**Comment by PerfectSlayer** [comment]
Ok thanks.
So @0-kaladin should update the translation as said in https://github.com/AdAway/AdAway/pull/969
Can't do more for now 😅

**Pull request merged**
