### PR TITLE
Add systemless support for MagiskSU

### PR DESCRIPTION
**Pull request by PerfectSlayer**
MagiskSU will now be detected.
If installed, the systemless settings will be enabled and checked accoring the current systemless status.
Pressing the AdAways settings will open the Magisk settings (with a hack, check at the source for the whole details) and coming back from the Magisk settings will update the AdAway systemless settings state. No
reboot is needed.

### CODE REVIEW

**Comment by knox** [comment]
@dschuermann since magisk has become the state of the art rooting solution this merge should make it into adaway, thanks!

**Comment by dschuermann** [comment]
Please discuss with @PerfectSlayer

**Comment by knox** [comment]
@PerfectSlayer are you going to resolve the conflicts so this can be merged? Thanks a lot.

**Comment by PerfectSlayer** [comment]
@knox Nope, I won't merge this PR.
In fact, a lot of work has been done to support different root solutions (Magisk included) in the next version.
It is not released yet but as you could see, it include the last Magisk systemless host support: https://github.com/PerfectSlayer/AdAway/commit/f2cc3fac7e00f6699c4987e4fee5d6c580234a59

If you want to test the dev build, check[ the XDA thread](https://forum.xda-developers.com/showpost.php?p=76438086&postcount=10983).

**Pull request closed without merging**
