### PR TITLE
Add systemless support check

### PR DESCRIPTION
**Pull request by PerfectSlayer**
There is two improvements:
- The systemless mode option will be only enabled if SuperSU >=2.56 is installed.
- The systemless mode will be checked if a mount point for /system/etc/hosts file is found (the ````0000adaway.script```` presence is no more checked)

That implies:
- The option will no be enabled for old version of SuperSU (without systemless support),
- The option will be checked for user with phh's Superuser and Magisk installed (as it creates a mount bind file for hosts by default). This will indicate user the feature is live but AdAway can't handle (enable or disable) it by itself.

### CODE REVIEW

**Comment by 0-kaladin** [comment]
@PerfectSlayer can you resolve the conflicts?  translations were updated so conflicts with your strings edits now.
@dschuermann  should those be done at transifex?

**Comment by dschuermann** [comment]
Yep, translations should be done on transifex. Maybe this should be mentioned in the README...

**Comment by PerfectSlayer** [comment]
@0-kaladin Sorry, I didn't know for the locales… Would you prefer I merge the locales or I use the ones that come from transifex (so you can keep updating the locales without blocking the PR if not merged quickly) ?

**Comment by dschuermann** [comment]
If we do a transifex updates, local changes in git will be overwritten, so it makes no difference.

**Comment by PerfectSlayer** [comment]
Ok. It should be done by the end of the week.
I also need to rework preferences in case of systemless root.

**Comment by PerfectSlayer** [comment]
@0-kaladin I have nothing else to add for the now.
You could merge it.

**Comment by 0-kaladin** [comment]
thanks @PerfectSlayer 
think i should just push as 3.2 or wait until you want to do any preferences stuff?  
otherwise I can post as a 3.2 preview 2 for now.  put on xda and labs for people to try out.

**Pull request merged**
