### PR TITLE
UI tewaks

### PR DESCRIPTION
**Pull request by brijrajparmar27**
minor visual tweaks including 
- adding support behind overlapping icons, goes along pretty well with the overall app design philosophy.
- adding colours to the main stat card icons making them eye catchy and easy to understand now that they look different from each other.(colours chosen according to the revised UI guidelines)

Before:
before
After:
after

### CODE REVIEW

**Comment by PerfectSlayer** [comment]
Hello @brijrajparmar27 

Thanks for your contribution! It is very interesting 👍 

> adding support behind overlapping icons, goes along pretty well with the overall app design philosophy.

Agreed. I tried to do it previously but did not published it because I try to match the same shape than the « pause » ad-blocking button. It is not a straight cut but corners are rounded. I try to edit your screenshot (using paint 😅 ) to show the difference:

image

image image


> adding colours to the main stat card icons making them eye catchy and easy to understand now that they look different from each other.(colours chosen according to the revised UI guidelines)

I never dared to add colors in the V5. I tried to keep the app meaningful without using colors (not sure I succeed) due to color-blind people. But I admit it looks great.
Maybe I would have picked more saturated color but they should be perfect for light theme.

So, what do you want about matching the softer angles? Any idea how to make them ? 😇 
It may be related to [vector drawables](https://developer.android.com/guide/topics/graphics/vector-drawable-resources) or MaterialShapeDrawable. I haven't dig further yet.

**Comment by brijrajparmar27** [comment]
> I try to match the same shape than the « pause » ad-blocking button. It is not a straight cut but corners are rounded.
not only i completely agree with you i tried to do that in the first place, the thing is i thought by setting the radius just the right amount i could achieve the curve but i was wrong setting the radius didn't gave the desired effect the only thing it did was make it more boxy, the funny thing is most people won't be able to notice that irrespectively.

> without using colors (not sure I succeed) due to color-blind people. But I admit it looks great.
😂😂😂😂😂

> Maybe I would have picked more saturated color but they should be perfect for light theme.
see that's the thing, I've been using this app for a long time now i was really happy to see the new UI back when this one was implemented but the one thing that bugged me was the colours, till now, making apps myself i have sticked to the Material design philosophy as it is based on actual research of colors and how our mind perceive them.
[https://material.io/design/color/dark-theme.html#behavior](url)
i am out on words on how to explain it to you but the above link explains in pretty good, that is the material io official site
you can practically see it yourself

desaturated washed colors on dark theme, easy on the eyes, high readability
dark(should be)

high saturation colors on dark theme, strains eyes, low readability
har to look at

but i was hesitant to make too many changes  in my first contribution, didn't knew if you would like it, i used material colors in those icons on purpose because here, look at this.
Screenshot from 2021-06-15 09-02-40
my eyes will start to bleed if i look at it for too long.
jokes apart, let me know what you feel...
i love this app, been using it for years now and i could help you with the colors if you'd like that.

**Comment by brijrajparmar27** [comment]
@PerfectSlayer may i have some feedback, what do you think? :)

**Comment by PerfectSlayer** [comment]
> most people won't be able to notice that irrespectively.

I will notice it 😉 

> i am out on words on how to explain it to you but the above link explains in pretty good, that is the material io official site
you can practically see it yourself

I read it and I understand why you are trying to explain.

> desaturated washed colors on dark theme, easy on the eyes, high readability

Now I can compare both render, I admit your choice looks better.

> but i was hesitant to make too many changes in my first contribution, didn't knew if you would like it, i used material colors in those icons on purpose because here, look at this.

I think that it the good approach (for AdAway like any other project). You can always risk to see all your work rejected if it goes to far or on the wrong direction for the maintainer. Better exchange first and be sure you have the same vision. Thanks for doing this way!

> i love this app, been using it for years now and i could help you with the colors if you'd like that.
what I'm suggesting is using light primary colors with dark theme and saturated signature color of adaway on lite theme (the opposite of what is currently implemented)

As you can see, I am not a UI expert so any help is welcome! We can start small (as you did) but if you are interested, feel free to exchange and talk about any change or evolution you can think of and want to implement. We can also reach the XDA forum and confront ideas and screenshots to check if we are going in the right direction 😅  

> may i have some feedback, what do you think? :)

Sure, you deserve it. I just struggle to find free time [with my recent burnout](https://forum.xda-developers.com/t/app-root-nonroot-official-adaway-v5-6-0.2190753/page-800#post-84764735). So don't be offended if you don't get an answer within a week, I might have some time / stress issues at the time. Be sure I am always glad when someone is interested to help me with this project, specially for the UI part 😊

**Comment by brijrajparmar27** [comment]
> I will notice it wink

fair enough XD

> Now I can compare both render, I admit your choice looks better.

i'm really glad you liked it

> You can always risk to see all your work rejected if it goes to far or on the wrong direction for the maintainer.

i totally agree, i have seen this happen.

> Better exchange first and be sure you have the same vision. Thanks for doing this way!

as of now i see the following improvements can be meaningful

- Home UI, the changes i did on the pull request were minor if you give me a free hand i would like the opportunity to redesign home 
Adaway

- the checkbox currently used look very dated, i would suggest replacing them with toggles (cupertino) 
image
image

- the colors need to be revised as i told you above according to material guidelines 
   `desaturated washed colors on dark theme, easy on the eyes, high readability`
- one thing i noticed was that the StevenBlack hosts already contains almost all the hosts from Adaway and Pete Lowe, this redundancy will only result in eating time everytime applying/editing or in dealing of any kind with hosts file, i know you are concerned about the event in which the Stevenlack hosts are down for some reason the app can fallback on the other two host sources but in my opinion there is a very little probability of that going down and as per me it would be unwise to voluntarily slow down the app on basis of such low probability, what we can do is clone the hosts and make the app fall back to the cloned source if the target hosts are not found, that would be an much healthier approach.
- one more thing, i have been using the app for a while and i use it to block all kinds of sites i am sure major of the user-base do too, StevenBlack has some amazing host collections that get updated in a consistent manner, i suggest letting the user decide what hosts do they want blocked like ads,porn,social etc... we could ask them this during the on-boarding slides itself "here are the stuff you can block -ads, -porn, -social, please select the ones you'd want to block"

> if you are interested, feel free to exchange and talk about any change or evolution you can think of and want to implement.

as you mentioned, i would love to help with the UI part also considering your concerns about the app getting rejected do you have any ideas on how do we collaborate?
i have listed every change i desire to contribute on adaway, it would be great if you could tell me the ones you like and would like me to start working on, we can always internally show these to people and get their opinion if they like these too.

> I just struggle to find free time with my recent burnout. So don't be offended if you don't get an answer within a week

i wish you a speedy recovery, work can get the best of us sometimes, i totally understand, i would suggest taking some good rest until you feel better again.

i hope you get better soon,
let me know of what you thing of the stuff i suggested so that maybe i can start working on them in my free time,

regards.

**Comment by PerfectSlayer** [comment]
That's a big list!

Let's focus on the home screen improvement and see how we can build from here.
I post your proposal on [the new version announcement post](https://forum.xda-developers.com/t/app-root-nonroot-official-adaway-v5-7-0.2190753/page-810#post-85246239). I hope we will get some feedback.

---

I'll just throw some answers that come to my mind without any specific order:

> he checkbox currently used look very dated, i would suggest replacing them with toggles (cupertino)

They come from AndroidX preference library. I might have miss something because I don't have toggle for boolean settings.

> the colors need to be revised as i told you above according to material guidelines

Yes, we need to make some render with the new colors and see if users don't complain too much. But I agree it would look better.

> one thing i noticed was that the StevenBlack hosts already contains almost all the hosts from Adaway

Yes, that is the purpose of list aggregator. We (mainly jawz101!) will keep maintaining our list as it provides us our independence and a lot of projects are depending on us. Adding StevenBlack is to get more ad-networks covered but honestly, our list should be enough for most of users.

>  i suggest letting the user decide what hosts do they want blocked like ads,porn,social etc...

I thought about it but never had the energy to do it. As a first step, I would like to integrate https://filterlists.com/ API to allow user to quickly add new specific source. It should allow to improve source discovery too.

**Comment by PerfectSlayer** [comment]
Hi @brijrajparmar27 

How are you?

I was just thinking lately to create a beta channel for the UI improvements?
So we can iterate and publish versions and gather feedback of the app more quickly.
What do you think about it?

**Comment by brijrajparmar27** [comment]
sorry for the late reply, i was tangled in a college academic matter.. :)

> That's a big list!
that tends to happen when people who can code use an app for long time, lol

> Let's focus on the home screen improvement and see how we can build from here.
yeah, starting small can be good.

> But I agree it would look better.
i'm happy to hear that.

> I would like to integrate https://filterlists.com/ API 
wow, indeed that would be great, that looks cool.

> I was just thinking lately to create a beta channel for the UI improvements?
a beta channel would be great, i will be nice to see the app UI updated to a modern one.
i really wanted to contribute towards this, to be honest i haven done much development in native android as i'm not particularly a fan of it (too much boilerplate code), i am more of a flutter guy.

> What do you think about it?
i think that's a really great idea, let me know when you create it so that i can start making pull requests.

also, if we could find a decent communication medium that would be great, i recall you mentioned XDA, i have an account though i'm not really active, i guess this could be a start.

**Review by PerfectSlayer — APPROVED** [review]

**Comment by PerfectSlayer** [comment]
I created a branch `feature/ui` dedicated to this beta. I will publish version when we feel confident to share the progress.
I merged your PR within (thanks!) and also updated the settings checkbox for switches.

Can you reach by PM on XDA? I can send you an invite for the private slack (where other contributors are also present). I am not the biggest fan nor the most active user of slack but it is useful for async communication.

I did few test with your changes. I think it misses color for the Day (light) theme and icon (the card added) are not clickable.
I will try to see if I can make a single shape based on vector drawable instead.

**Comment by brijrajparmar27** [comment]
> I created a branch feature/ui dedicated to this beta. 

cool, just fetched it...

> Can you reach by PM on XDA

sure, just did.

> I can send you an invite for the private slack

that would be great, i'll ping you my email on XDA

> I think it misses color for the Day (light) theme

thats odd, do you mean to say theming isnt being applied to UI Elements?

> icon (the card added) are not clickable.

just saw, didn't think of that while adding it, you're right vector drawable would have been the way to go.

**Pull request merged**
