### PR TITLE
More intuitive clear DNS request list icon

### PR DESCRIPTION
**Pull request by damoasda**
When I was using the DNS requests log I didn't find the clear button icon very intuitive. So I suggest to replace it by a more intuitive icon, see screenshot:

icon-change

To see the page go to Menu &rarr; Log DNS requests &rarr; Show results.

### CODE REVIEW

**Comment by PerfectSlayer** [comment]
Hello @damoasda 
Thanks for your contribution!

The icon comes from Android material design icons site.
This is the _clear all_ icon from _communication_ section.

It expresses the fact you dismiss all events from your log. What is wrong about it?
With the _delete foverer_, it looks more I am deleting something from my device.

As log is not user content, but more generated output, I though clear was more appropriate at the time.
I am looking for more examples from Google and others apps to find which one is the best.
If you have some, feel free to share!

**Comment by damoasda** [comment]
Thanks for clarifying.

I saw the _clear all_ icon for my first time and I was wondering what it would do, it looks like another sorting icon. The idea to replace it by a dust bin icon was inspired by Android Studio:

intellij-delete-icon

Technically, I fully agree with you, the _clear all_ icon is the intended one by Android. From user's perspective I couldn't image what it means, but now I know. :smiley:

As you know AdAway's user base much better than me, you can decide if it is of relevance.

**Comment by PerfectSlayer** [comment]
Damned… Android Studio is not the only one!

image

I am more what they call a _backend engineer_, or a _software architect_. I try to do the best UI I can but sometime it is not enough. If my users tells me an icon is wrong, I think they are more qualified than me for this task! Especially when others apps give them right 😅 

I will merge the PR and update the icons (trash and pen) in the same time (Google changed the preferred icon style from plain to outline only).

Thanks for your contribution!
I hope you enjoy the app 😉

**Comment by damoasda** [comment]
@PerfectSlayer, thank you very much for optimizing the buttons.

Indeed, I enjoy AdAway a lot. The last time I checked my Android log the only Exceptions I could see were related to AdAway:
`ConnectException: Failed to connect to reports.crashlytics.com/0.0.0.0:443`
:joy: :joy: :joy:
Great work, thank you! :+1:

**Pull request merged**
