### PR TITLE
Fix for Android N, Gradle cleanup

### PR DESCRIPTION
**Pull request by sanjay900**
ToyBox requires a slightly modified set of arguments, and it turns out that ToolBox never required the mount arguments, so fixing the mount path finder for nougat wasn't worth it and i got rid of it alltogether. However, now you need to pass the mount to RootCommands.Remounter.remount, not the file 
#770

### CODE REVIEW

**Comment by sanjay900** [comment]
@KreAch3R This a better fix?

**Comment by 0-kaladin** [comment]
@sanjay900 thanks for this.  can you resolve the conflicts and update the pull request?

**Comment by sanjay900** [comment]
@0-kaladin done

**Comment by sanjay900** [comment]
I also figured it was time to update gradle, so i fixed the jni for that, and also removed a bunch of libraries and just made them gradle dependancies.

**Comment by 0-kaladin** [comment]
yep, i love keeping gradle updated.  thanks!

**Comment by sanjay900** [comment]
Shoot, i just realised a big bug with i just did

**Pull request merged**
