### PR TITLE
Add support for ChainFire's SuperSU "bind sbin"

### PR DESCRIPTION
**Pull request by PerfectSlayer**
Add support the the latest systemless sbin mode aka "bind sbin" mode.
Tested on Android 7.1 with ChainFire's SuperSU 2.82-SR3 with the following modes:
- "/su partition" systemless
- "bind sbin" systemless

### CODE REVIEW

**Comment by fwhem** [comment]
Working good on angler w/ stock O and SuperSU 2.82-SR3. Thanks @PerfectSlayer                             https://github.com/fwhem/AdAway/commits/master

**Comment by PerfectSlayer** [comment]
And thanks for the feedback @fwhem !

**Comment by Techman-** [comment]
People still use SuperSU? I thought all sane humans converted away to Magisk 😀

**Comment by fwhem** [comment]
@Techman-  I actually play with both but only use SuperSU zips built and supplied by Chaninfire from his server. So not insane LOL.

**Comment by Joshndroid** [comment]
This is definitely what we need. currently doing this manually from what i have seen on the web....

@Techman- magisk su was my go too until oreo then it was extremely inconsistent whereas supersu works first time everytime for me

**Comment by guest4711** [comment]
Nagisk is not available for my S2 i9100.

**Pull request merged**
