### PR TITLE
New feature: Show latest hosts file diff

### PR DESCRIPTION
**Pull request by damoasda**
After a hosts file update I'm interested to see the changes (diff). For this I added a feature that works quite well for me and I'm happy to contribute it to AdAway if you are interested.

Steps to show the hosts diff:

1. Click on the burger button
2. Open hosts file
3. Scroll to the bottom, there is a new button "Show latest changes". Click on it.
4. You can see a diff of the latest hosts changes.

Implementation details:

- The button "Show latest changes" is greyed out if AdAway hasn't been activated and thus hasn't modified the hosts file yet.
- The diff view shows maximum 50 lines.
- Internally, the Android hosts file is copied to a private file `hosts_backup` before the update. It is used to calculate the diff.
- I refactored the classes `HostsInstallModel` and `ApplyUtils` and extracted a method `getAndroidHostsFilename()` to avoid code duplication.
- New dependency to `java-diff-utils` for the diff algorithm.

### CODE REVIEW

**Comment by PerfectSlayer** [comment]
Hello @damoasda 

Thanks for your idea and your contribution!
I am quite busy right now but I can already provide you some feedback.

First, I think the feature to provide a (merged) hosts changelog is a good idea.
I don't really know who can be interested: other list makers? someone with an app which recently stopped working? But it's nice to have.

For now, I still have some questions:
1. If users have automatic update enabled, they can only see the changes from the last day? (as auto-update is on a daily basis and AdAway hosts file is being actively updated right now 😅 )
2. What happens if a users temporary disable then reanable adblocking? Is diff still available?
3. The next version of AdAway changes a lot of internal stuff. All hosts entries are now in a database and hosts file is not always generated (when the adblocking does not use root). I wonder how I could maintain a such feature with the new plumbing.

**Comment by damoasda** [comment]
@PerfectSlayer, thank you for the insights into the future plans for AdAway. I agree that every feature requires a certain maintainance effort in the future, so the feature should have at least a relevant value for many users what I cannot estimate. I don't mind if you cancel the pull request, I still can use it on my phone. :-)

Regarding your questions:

1. Yes, at the moment users with automatic update enabled can only see the changes from the last day.
2. If a user temporary disables and enables adblocking, the diff is quite slow and huge, because it compares the small default hosts file with the long merged hosts file. But this could be improved easily if required.
3. See above.

**Comment by Kronopt** [comment]
I think this would be a nice feature to have.
I like changelogs. This would fulfill my changelog needs for AdAway 😄

**Comment by PerfectSlayer** [comment]
@Kronopt Could you describe and explain your changelog need?
It could help me to refine this feature and think how to integrate it in the next app version.

**Comment by Kronopt** [comment]
Well, I like to know what's different with new software updates.
In the case of AdAway, I don't really know what's been added or deleted from the hosts file when it is updated.
Having that information after each update would be nice.

**Comment by gvoze32** [comment]
I think changelog feature is very nice and useful

**Comment by damoasda** [comment]
The changes in this pull request do not fit to AdAway version 5 as the internal data structure and the UI has changed fundamentally. So I close this pull request.

**Pull request closed without merging**
